version: 2.0
jobs:
  tests:
    docker:
      - image: circleci/node:8.9.4-browsers
    steps:
      - checkout
      - restore_cache:
          key: everywhere-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: everywhere-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            npm run test
  coverage:
    docker:
      - image: circleci/node:8.9.4-browsers
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get install jq
      - restore_cache:
          key: everywhere-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: everywhere-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run coverage
          command: |
            npm run coverage
      - run:
          name: Publish coverage on PR
          command: |
            export PATH="$PATH:~/.local/bin"
            bash ./scripts/post-coverage-to-github.sh $CIRCLE_BRANCH
workflows:
  version: 2
  commit-workflow:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - gh-pages
      - coverage:
          filters:
            branches:
              ignore:
                - gh-pages
                - master