version: 2.1

restore-workspace: &restore-workspace
  attach_workspace:
    at: ~/

publish-filter: &publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+(\.[0-9]+)*$/

gh-pages-filter: &gh-pages-filter
  branches:
    ignore: gh-pages

executors:
  node:
    docker:
      - image: circleci/node:10.11.0-browsers
    working_directory: ~/aircall-everywhere

jobs:
  checkout-install-node-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: aircall-everywhere-node-modules{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: aircall-everywhere-node-modules{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: ~/
          paths: aircall-everywhere

  test:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn test

  coverage:
    executor: node
    steps:
      - *restore-workspace
      - run: |
          sudo rm /etc/apt/sources.list
          echo "deb http://deb.debian.org/debian jessie main" | sudo tee -a /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
          echo "Acquire::Check-Valid-Until false;" | sudo tee -a /etc/apt/apt.conf.d/10-nocheckvalid
          echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | sudo tee -a /etc/apt/preferences.d/10-archive-pin
          sudo apt-get update
      - run: sudo apt-get install libonig2 && sudo apt-get install libjq1 &&  sudo apt-get install jq && sudo apt-get install bc
      - run: yarn coverage
      - run:
          name: Publish coverage on PR
          command: |
            export PATH="$PATH:~/.local/bin"
            bash ./scripts/post-coverage-to-github.sh $CIRCLE_BRANCH

  build-prod:
    executor: node
    steps:
      - *restore-workspace
      - run: yarn build
      - persist_to_workspace:
          root: ~/
          paths: aircall-everywhere/dist

  npm-publish:
    executor: node
    steps:
      - *restore-workspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/aircall-everywhere/.npmrc
      - run: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout-install-node-dependencies
      - test:
          requires: [checkout-install-node-dependencies]
          filters: *gh-pages-filter

      - coverage:
          requires: [test]
          filters:
            branches:
              ignore: gh-pages
                master

      - build-prod:
          requires: [test]
          filters: *gh-pages-filter

      - approve-publish:
          type: approval
          requires: [build-prod]
          filters: *publish-filter

      - npm-publish:
          requires: [approve-publish]
          filters: *publish-filter
